---
# tasks file for dockerTomcat

#Recuperer maven artifact
- name: download mavane artifact
  maven_artifact:
    group_id: org.jenkins.main
    artifact_id: WebApp
    version: latest
    extension: war
    repository_url: 'http://172.16.30.102:8081/repository/nexusrep/'
    username: admin
    password: admin
    dest: /home/benjixxx/webAppVolume


- name: Changer la permission du fichier war de destination
  shell: sudo chmod 755 /home/benjixxx/webAppVolume/*.war

#Création du container tomcat 
- name: création container tomcat
  docker_container:
    name: tomcat
    image: tomcat:8.0
    ports:
    - "8889:8080"
    volumes:
    - /home/benjixxx/webAppVolume/:/usr/local/tomcat/webapps

# Création deuxiéme container tomcat
- name: création  deuxiéme container tomcat
  docker_container:
    name: tomcat2
    image: tomcat:8.0
    ports:
    - "8890:8080"
    volumes:
    - /home/benjixxx/webAppVolume/:/usr/local/tomcat/webapps
  
    
  

